language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key: 2cd37ceb-51fc-4dd7-82e5-42de68a9d15b
  app: lit-hamlet-54666
  on:
    repo: Robp773/ultra-light-backpacking-api